# Generated by Django 4.2.10 on 2024-04-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooknowsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='issue_type',
            field=models.CharField(choices=[('professors', 'Professor'), ('teaching_assistant', 'Teaching Assistant'), ('homework_assignments', 'Homework Assignment'), ('course_logistics', 'Course Logistics'), ('tests_exams', 'Test/Exam'), ('others', 'Other')], default='others', max_length=30, verbose_name='Related to'),
        ),
    ]
