# Generated by Django 4.2.11 on 2024-04-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooknowsapp', '0002_alter_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='issue_type',
            field=models.CharField(choices=[('professors', 'Professors'), ('teaching_assistant', 'Teaching Assistant'), ('homework_assignments', 'Homework Assignments'), ('course_logistics', 'Course Logistics'), ('tests_exams', 'Tests/Exams'), ('others', 'Others')], default='others', max_length=30, verbose_name='Related to'),
        ),
    ]
