# Generated by Django 4.2.6 on 2024-03-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hooknowsapp', '0002_remove_report_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
