# Generated by Django 4.2.11 on 2024-03-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hooknowsapp', '0002_remove_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
