# Generated by Django 4.2.6 on 2024-03-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooknowsapp', '0003_remove_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(default='null', upload_to='reports/'),
            preserve_default=False,
        ),
    ]
