# Generated by Django 4.2.10 on 2024-03-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hooknowsapp', '0005_alter_report_user_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
