# Generated by Django 4.2.10 on 2024-03-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooknowsapp', '0008_report_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='slug',
        ),
        migrations.AddField(
            model_name='report',
            name='report_description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
