# Generated by Django 4.2.10 on 2024-03-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hooknowsapp', '0009_remove_report_slug_report_report_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_description',
            new_name='description',
        ),
    ]
