# Generated by Django 4.2.6 on 2024-03-30 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hooknowsapp', '0010_rename_report_description_report_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to='hooknowsapp.report')),
            ],
        ),
    ]
