# Generated by Django 4.2.6 on 2024-04-14 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hooknowsapp', '0012_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
