# Generated by Django 4.2.6 on 2024-03-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooknowsapp', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default='', max_length=200),
        ),
    ]
